### PR TITLE
feat(python-sdk): experimental marimo cookie support

### PR DESCRIPTION
**Pull request by jfeodor**
Load cookies in marimo apps with `numerous.experimental.marimo.cookies`.

In order to use the above function, either:
1. run the marimo notebook with `python -m numerous marimo run` (as
   opposed to `marimo run`) which will launch the app with a modified
   marimo server that enables reading cookies.
3. If adding the marimo app to a fastapi app with
   `marimo.create_asgi_app()`, use `add_marimo_cookie_middleware` to add
   cookie middleware to the fastapi app.

### CODE REVIEW

**Comment by mrdobalina2k** [comment]
This looks a bit hackish, yet appears like an ok compromise which will work well, though I personally think setting the user id as a client side cookie is a better and more generic approach, that will work for regardless of the app framework. 

For this implementation however, could you add the feature that we could use the cli like: numerous marimo run/edit ...?

**Comment by jfeodor** [comment]
> This looks a bit hackish, yet appears like an ok compromise which will work well, though I personally think setting the user id as a client side cookie is a better and more generic approach, that will work regardless of the app framework.
> 
> For this implementation however, could you add the feature that we could use the cli like: numerous marimo run/edit ...?

We are looking into the implications of exposing the user information on the client side, but it seems likely that it will be insecure, so this approach is better. You can consider it a bit of a hack, since we are monkeypatching marimo to achieve the functionality that is not yet implemented in marimo.

It will not be added to the regular CLI as it stands right now, as it is an experimental feature.

**Comment by mikhailNumerous** [comment]
Looks good.

Since `_thread_ident` and `_proc_ident` are a kind of cookies IDs, is it correct that marimo handles different users sessions in different threads?
If no, maybe later it worth to consider using the internal marimo session ID as a key to be passed  to `Cookies` `get` and `set` methods.

**Comment by mrdobalina2k** [comment]
I am wondering why you consider having a user id stored on the client side can be considered unsafe? A user id should itself not contain any sensitive information. You could also use an alias, which is not the actual user ID, but unique to that user anyway, if you were afraid of exposing sensitive data in the browser.

**Comment by mrdobalina2k** [comment]
We could also use the example on https://docs.marimo.io/guides/deploying/programmatically.html, similarly to your suggestion, but instead of overwriting the route to /instantiate, we could add middleware that stores the cookie if a call to /instantiate is found. This would prevent any monkey patching.

**Comment by jfeodor** [comment]
> I am wondering why you consider having a user id stored on the client side as unsafe? A user id should itself not contain any sensitive information. You could also use an alias, which is not the actual user ID, but unique to that user anyway, if you were afraid of exposing sensitive data in the browser.

It is insecure because it relies on authenticating the user based on a public value (user ID) that is not signed. This means that a user of an app might be able to spoof the user ID and impersonate another user.

**Pull request merged**
